### PR TITLE
link to tutorial in rendered (not source) format

### PR DESCRIPTION
**Pull request by holtzermann17**
rawgit provides a nice service for this

### CODE REVIEW

**Comment by avigad** [comment]
Thanks, Joe. This is good to know. I am afraid to merge the request because nobody is actively working on the project, and so I'd rather keep the 2015 date of the last commit. (@robertylewis do you agree?)

By the way, see also https://github.com/robertylewis/lean_polya.

**Comment by robertylewis** [comment]
Agreed. By the way, I have some local work on Polya-in-Lean. Expect some activity on that repo reasonably soon. But I don't think it makes sense to touch this one right now.

**Comment by avigad** [comment]
It would be wonderful if Lean's Polya became robust enough for everyday use.

**Comment by robertylewis** [comment]
In Orsay I factored out the linear arithmetic portion for mathlib (https://github.com/leanprover/mathlib/blob/master/tactic/linarith.lean). Mario made some improvements to his `ring` tactic, and I think it's now robust enough to do a lot of the normalization in Polya that was being done adhoc or was sorried.

**Comment by holtzermann17** [comment]
Hi guys!  I guess this will sit on the network and can be snuck in if activity resumes. I'm currently studying both versions of Polya, and related systems - I'll try and explain my interest by email.

**Comment by codyroux** [comment]
Probably a moot point at this stage, but git commit --amend allows
commiting without changing the date, and the date can be changed
retroactively for any commit: https://stackoverflow.com/a/41997774/2059388

I can obviously understand any reluctance at git wizardry at this point
though.

**Pull request closed without merging**
